// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0BuycnFwZNpaEUU9uIHEuriCJbzHJb4',
    appId: '1:116193289030:web:f15c904c9dd46ca25dfb47',
    messagingSenderId: '116193289030',
    projectId: 'resolveu-69469',
    authDomain: 'resolveu-69469.firebaseapp.com',
    storageBucket: 'resolveu-69469.firebasestorage.app',
    measurementId: 'G-NLLKGTCESM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcjt6F6y5kgbljw7unsqsUh4M00AA9u0',
    appId: '1:116193289030:android:cb5a9e4dd449a63b5dfb47',
    messagingSenderId: '116193289030',
    projectId: 'resolveu-69469',
    storageBucket: 'resolveu-69469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzDQN-e-PxShFHZHJW2Vy20eZQO-pdmVo',
    appId: '1:116193289030:ios:a931c3def0bf56295dfb47',
    messagingSenderId: '116193289030',
    projectId: 'resolveu-69469',
    storageBucket: 'resolveu-69469.firebasestorage.app',
    iosBundleId: 'com.example.resolveu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzDQN-e-PxShFHZHJW2Vy20eZQO-pdmVo',
    appId: '1:116193289030:ios:a931c3def0bf56295dfb47',
    messagingSenderId: '116193289030',
    projectId: 'resolveu-69469',
    storageBucket: 'resolveu-69469.firebasestorage.app',
    iosBundleId: 'com.example.resolveu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU0BuycnFwZNpaEUU9uIHEuriCJbzHJb4',
    appId: '1:116193289030:web:8d5be7e0bc8933215dfb47',
    messagingSenderId: '116193289030',
    projectId: 'resolveu-69469',
    authDomain: 'resolveu-69469.firebaseapp.com',
    storageBucket: 'resolveu-69469.firebasestorage.app',
    measurementId: 'G-KQ8S0NC8Z5',
  );
}
